// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TeleQuick.Business.Models
{
    public partial class InvoiceDetail
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(5)]
        public string Date { get; set; }
        public string Hour { get; set; }
        public string TollStation { get; set; }
        public string Way { get; set; }
        public int Categoria { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Total { get; set; }
        public int? InvoiceHeaderId { get; set; }

        [ForeignKey(nameof(InvoiceHeaderId))]
        [InverseProperty("InvoiceDetails")]
        public virtual InvoiceHeader InvoiceHeader { get; set; }
    }
}