// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TeleQuick.Business.Models
{
    public partial class TagRfid
    {
        [Key]
        public int Id { get; set; }
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [StringLength(256)]
        public string UpdatedBy { get; set; }
        public DateTime UpdatedDate { get; set; }
        public DateTime CreatedDate { get; set; }
        [Column("TAGNumber")]
        public int Tagnumber { get; set; }
        [Column("TAGEneable")]
        public bool Tageneable { get; set; }
        public int? VehicleId { get; set; }

        [ForeignKey(nameof(VehicleId))]
        [InverseProperty("TagRfids")]
        public virtual Vehicle Vehicle { get; set; }
    }
}