// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using TeleQuick.Business.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using TeleQuick.Business.Models;

namespace TeleQuick.DataAcces
{
    public partial class ApplicationDbContext 
    {
        public ApplicationDbContext()
        {
        }

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<AccountSession> AccountSessions { get; set; }
        public virtual DbSet<Concessionary> Concessionaries { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<InvoiceHeader> InvoiceHeaders { get; set; }
        public virtual DbSet<TagRfid> TagRfids { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<AccountSession>(entity =>
            {
                entity.HasIndex(e => e.ConcessionaryId);
            });

            modelBuilder.Entity<Concessionary>(entity =>
            {
                entity.Property(e => e.MainForm).HasDefaultValueSql("(N'')");

                entity.Property(e => e.Uri).HasDefaultValueSql("(N'')");
            });

            modelBuilder.Entity<InvoiceDetail>(entity =>
            {
                entity.HasIndex(e => e.InvoiceHeaderId);
            });

            modelBuilder.Entity<InvoiceHeader>(entity =>
            {
                entity.HasIndex(e => e.VehicleId);
            });

            modelBuilder.Entity<TagRfid>(entity =>
            {
                entity.HasIndex(e => e.VehicleId);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}