// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TeleQuick.Business.Models
{
    public partial class AccountSession
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string LoginUser { get; set; }
        [Required]
        [StringLength(50)]
        public string LoginUserPassword { get; set; }
        public bool IsValid { get; set; }
        public int ConcessionaryId { get; set; }
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [StringLength(256)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime UpdatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }

        [ForeignKey(nameof(ConcessionaryId))]
        [InverseProperty("AccountSessions")]
        public virtual Concessionary Concessionary { get; set; }
    }
}