// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TeleQuick.Business.Models
{
    public partial class Concessionary
    {
        public Concessionary()
        {
            AccountSessions = new HashSet<AccountSession>();
            InvoiceHeaders = new HashSet<InvoiceHeader>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(30)]
        public string Name { get; set; }
        [Required]
        [StringLength(200)]
        public string Detail { get; set; }
        [Required]
        [StringLength(50)]
        public string MainForm { get; set; }
        [Required]
        [StringLength(500)]
        public string Uri { get; set; }

        [InverseProperty(nameof(AccountSession.Concessionary))]
        public virtual ICollection<AccountSession> AccountSessions { get; set; }
        [InverseProperty(nameof(InvoiceHeader.Concessionary))]
        public virtual ICollection<InvoiceHeader> InvoiceHeaders { get; set; }
    }
}