// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TeleQuick.Business.Models
{
    public partial class InvoiceDetail
    {
        [Key]
        public int Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime Date { get; set; }
        public TimeSpan Hour { get; set; }
        public int Quantity { get; set; }
        [Required]
        [StringLength(50)]
        public string TollStation { get; set; }
        [Required]
        [StringLength(5)]
        public string Way { get; set; }
        public int Categoria { get; set; }
        [Column(TypeName = "decimal(6, 2)")]
        public decimal Total { get; set; }
        public int InvoiceHeaderId { get; set; }
        public int VehicleId { get; set; }

        [ForeignKey(nameof(InvoiceHeaderId))]
        [InverseProperty("InvoiceDetails")]
        public virtual InvoiceHeader InvoiceHeader { get; set; }
        [ForeignKey(nameof(VehicleId))]
        [InverseProperty("InvoiceDetails")]
        public virtual Vehicle Vehicle { get; set; }
    }
}