// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TeleQuick.Business.Models
{
    public partial class Vehicle
    {
        public Vehicle()
        {
            InvoiceDetails = new HashSet<InvoiceDetail>();
            TagRfids = new HashSet<TagRfid>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Make { get; set; }
        [Required]
        [StringLength(50)]
        public string Model { get; set; }
        public int Year { get; set; }
        [Required]
        [StringLength(10)]
        public string RegistrationNumber { get; set; }
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [StringLength(256)]
        public string UpdatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime UpdatedDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }

        [InverseProperty(nameof(InvoiceDetail.Vehicle))]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        [InverseProperty(nameof(TagRfid.Vehicle))]
        public virtual ICollection<TagRfid> TagRfids { get; set; }
    }
}