// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TeleQuick.Business.Models.Interfaces;

namespace TeleQuick.Business.Models
{
    public partial class Vehicle : IAuditableEntity
    {
        
    }
}